theme: jekyll-theme-slate
title: "Inertial Odometry on Handheld Smartphones"
description: "<a href='http://arno.solin.fi'>Arno Solin</a>, <a href='#'>Santiago Cortes</a>, <a href='http://esa.rahtu.fi/'>Esa Rahtu</a>, and <a href='https://users.aalto.fi/~kannalj1/'>Juho Kannala</a><br />Published in FUSION 2018"
